package mapping;
// Generated Aug 15, 2018 9:34:27 AM by Hibernate Tools 4.3.1




import java.sql.Time;
import java.time.LocalTime;
import java.util.Date;


/**
 * Absensi generated by hbm2java
 */
public class Absensi  implements java.io.Serializable {

     
     private Integer absId;
     private TableUser tableUser;
     private Time jamIn;
     private Time jamOut;
     private Time lemburIn;
     private Time lemburOut;
     private Date tgl;

    public Absensi() {
    }

    public Absensi(TableUser tableUser, Date tgl, Time jamIn, Time jamOut, Time lemburIn, Time lemburOut) {
       this.tableUser = tableUser;
       this.tgl = tgl;
       this.jamIn = jamIn;
       this.jamOut = jamOut;
       this.lemburIn = lemburIn;
       this.lemburOut = lemburOut;
    }
   
    public Integer getAbsId() {
        return this.absId;
    }
    
    public void setAbsId(Integer absId) {
        this.absId = absId;
    }
    public TableUser getTableUser() {
        return this.tableUser;
    }
    
    public void setTableUser(TableUser tableUser) {
        this.tableUser = tableUser;
    }
    public Date getTgl() {
        return this.tgl;
    }
    
    public void setTgl(Date tgl) {
        this.tgl = tgl;
    }
    public Time getJamIn() {
        return this.jamIn;
    }
    
    public void setJamIn(Time jamIn) {
        this.jamIn = jamIn;
    }
    public Time getJamOut() {
        return this.jamOut;
    }
    
    public void setJamOut(Time jamOut) {
        this.jamOut = jamOut;
    }
    public Time getLemburIn() {
        return this.lemburIn;
    }
    
    public void setLemburIn(Time lemburIn) {
        this.lemburIn = lemburIn;
    }
    public Time getLemburOut() {
        return this.lemburOut;
    }
    
    public void setLemburOut(Time lemburOut) {
        this.lemburOut = lemburOut;
    }
    




}


