package mapping;
// Generated Aug 15, 2018 9:34:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TableUser generated by hbm2java
 */
public class TableUser  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private Set absensis = new HashSet(0);

    public TableUser() {
    }

    public TableUser(String userName, Set absensis) {
       this.userName = userName;
       this.absensis = absensis;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Set getAbsensis() {
        return this.absensis;
    }
    
    public void setAbsensis(Set absensis) {
        this.absensis = absensis;
    }




}


